title: Yonghao Shi's Homepage
page-top-title: Yonghao Shi
top-section-bg-text: Computer Science | Human Computer Interaction
home-subtitle: Yonghao Shi&ensp;|&ensp;史永皓
copyright-text: '&copy; Yonghao Shi 2024-2025. All Rights Reserved.'
